<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>performance-tests</artifactId>
	<version>1.0.0</version>

	<properties>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>

		<jmeter.maven.plugin.version>3.8.0</jmeter.maven.plugin.version>
	</properties>

	<build>

		<plugins>

			<plugin>
				<groupId>com.lazerycode.jmeter</groupId>
				<artifactId>jmeter-maven-plugin</artifactId>
				<version>${jmeter.maven.plugin.version}</version>

				<configuration>

					<testFilesIncluded>
						<jMeterTestFile>
							report-api-load.jmx
						</jMeterTestFile>
					</testFilesIncluded>

					<generateReports>true</generateReports>

				</configuration>

				<executions>

					<execution>
						<id>configuration</id>
						<goals>
							<goal>configure</goal>
						</goals>
					</execution>

					<execution>
						<id>jmeter-tests</id>
						<goals>
							<goal>jmeter</goal>
							<goal>results</goal>
						</goals>
					</execution>

				</executions>
			</plugin>

		</plugins>

	</build>

</project>